development:
  adapter: postgresql
  encoding: utf8
  database: simpletest_development
  pool: 5
  host: localhost

test: &test
  adapter: postgresql
  encoding: utf8
  database: simpletest_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: simpletest_production
  pool: 5

cucumber:
  <<: *test